media:
  - name: public-images
    label: Public Images
    input: public
    output: /public
    extensions: [png, jpg, jpeg, webp, svg, gif]
  - name: src-images
    label: Source Images
    input: src/images
    output: /src/images
    extensions: [png, jpg, jpeg, webp, svg, gif]

content:
  - name: authors
    label: Authors
    type: collection
    path: src/content/authors
    filename: "{name}.mdx"
    fields:
      - name: name
        label: Name
        type: string
        required: true
      - name: image
        label: Image
        type: image
        options:
          media: src-images
          path: src/images/folk
          extensions: [png, jpg, jpeg, webp, svg, gif]
        description: "Author profile image"
  - name: blogg
    label: Blog Posts
    type: collection
    path: src/content/blogg
    filename: "{year}-{month}-{day}-{title}.mdx"
    view:
      fields: [title, author, createdAt, hide]
      sort: [createdAt, title]
      default:
        sort: createdAt
        order: desc
    fields:
      - name: title
        label: Title
        type: string
        required: true
        description: "The title will be used in the filename (spaces and special chars will be sanitized)"
      - name: author
        label: Author
        type: reference
        required: true
        options:
          collection: authors
          label: "{name}"
          image: "{image}"
      - name: ingress
        label: Ingress
        type: text
        description: "Short description/intro text"
      - name: image
        label: Image
        type: image
        options:
          media: src-images
          path: src/images/blogg
          extensions: [png, jpg, jpeg, webp, svg, gif]
        description: "URL or path to the blog post image (should be landscape format)"
      - name: createdAt
        label: Created At
        type: date
        required: true
        options:
          time: true
          format: yyyy-MM-dd HH:mm
      - name: updatedAt
        label: Updated At
        type: date
        options:
          time: true
          format: yyyy-MM-dd HH:mm
      - name: hide
        label: Hide
        type: boolean
        default: false
        description: "Hide this post from the blog listing"
      - name: body
        label: Body
        type: rich-text
        options:
          media: src-images
          path: src/images/blogg
          extensions: [png, jpg, jpeg, webp, svg, gif]
        description: "Main content of the blog post"

settings:
  content:
    merge: true
