media:
  - name: public-images
    label: Bilder
    input: public
    output: /
    extensions: [png, jpg, jpeg, webp, svg, gif]
  - name: src-images
    label: Kode-bilder
    input: src/images
    output: /src/images
    extensions: [png, jpg, jpeg, webp, svg, gif]

content:
  - name: authors
    label: Forfattere
    type: collection
    path: src/content/authors
    filename: "{primary}.mdx"
    view:
      fields: [name, image]
      primary: name
    fields:
      - name: name
        label: Navn
        type: string
        required: true
      - name: image
        label: Bilde
        type: image
        options:
          media: src-images
          path: src/images/folk
          extensions: [png, jpg, jpeg, webp, svg, gif]
        description: "Forfatterprofilbilde"
  - name: blogg
    label: Blogginnlegg
    type: collection
    path: src/content/blogg
    filename: "{year}-{month}-{day}-{primary}.mdx"
    view:
      fields: [title, author, createdAt, hide]
      primary: title
      sort: [createdAt, title]
      default:
        sort: createdAt
        order: desc
    fields:
      - name: title
        label: Tittel
        type: string
        required: true
        description: "Tittelen vil også bli brukt i URL-en"
      - name: author
        label: Forfatter
        type: reference
        required: true
        options:
          collection: authors
          label: "{name}"
          image: "{image}"
      - name: ingress
        label: Ingress
        type: text
        options:
          rows: 2
          maxLength: 150
      - name: image
        label: Bilde
        type: image
        required: true
        options:
          media: public-images
          path: public/blogg
          extensions: [png, jpg, jpeg, webp, svg, gif]
        description: "Bør være landskapsformat"
      - name: createdAt
        label: Opprettet
        type: date
        required: true
        options:
          time: true
          format: yyyy-MM-dd HH:mm
      - name: updatedAt
        label: Oppdatert
        type: date
        options:
          time: true
          format: yyyy-MM-dd HH:mm
      - name: hide
        label: Skjul
        type: boolean
        default: false
        description: "Skjul dette innlegget fra blogglisten"
      - name: body
        label: Innhold
        type: rich-text
        options:
          media: public-images
          path: public/blogg
          extensions: [png, jpg, jpeg, webp, svg, gif]
  - name: festivalkomite
    label: Festivalkomite
    type: collection
    path: src/content/festivalkomite
    filename: "{primary}.mdx"
    view:
      fields: [title, filled, fee, start, end]
      primary: title
      sort: [filled, title]
      default:
        sort: filled
        order: asc
    fields:
      - name: title
        label: Tittel
        type: string
        required: true
        description: "Tittelen vil også bli brukt i URL-en"
      - name: fee
        label: Honorar
        type: boolean
        default: false
        description: "Om stillingen har honorar"
      - name: start
        label: Startdato
        type: string
        description: "Når stillingen starter (f.eks. '1. mai 2026')"
      - name: end
        label: Sluttdato
        type: string
        description: "Når stillingen slutter (f.eks. '1. august 2026')"
      - name: deadline
        label: Søknadsfrist
        type: string
        description: "Søknadsfrist (f.eks. '10. september 2025')"
      - name: filled
        label: Besatt
        type: boolean
        default: false
        description: "Om stillingen er besatt"
      - name: image
        label: Bilde
        type: image
        options:
          media: public-images
          path: public/festivalkomite
          extensions: [png, jpg, jpeg, webp, svg, gif]
        description: "Bilde for stillingen"
      - name: body
        label: Innhold
        type: rich-text
        options:
          media: public-images
          path: public/festivalkomite
          extensions: [png, jpg, jpeg, webp, svg, gif]
  - name: frivillig
    label: Frivillig
    type: collection
    path: src/content/frivillig
    filename: "{primary}.mdx"
    view:
      fields: [title]
      primary: title
      sort: [title]
    fields:
      - name: title
        label: Tittel
        type: string
        required: true
        description: "Tittelen vil også bli brukt i URL-en"
      - name: imagePath
        label: Bilde
        type: image
        options:
          media: src-images
          path: src/images/frivillig
          extensions: [png, jpg, jpeg, webp, svg, gif]
        description: "Bilde for frivilliggruppen"
      - name: imageAlt
        label: Bildebeskrivelse
        type: string
        description: "Alternativ tekst for bildet"
      - name: body
        label: Innhold
        type: rich-text
        options:
          media: public-images
          path: public/blogg
          extensions: [png, jpg, jpeg, webp, svg, gif]
  - name: artist
    label: Artister
    type: collection
    path: src/content/artist
    filename: "{primary}.mdx"
    view:
      fields: [title, tagline, concertStartAt, venue, hideFromArtistList, order]
      primary: title
      sort: [order, concertStartAt, title]
      default:
        sort: order
        order: asc
    fields:
      - name: title
        label: Navn
        type: string
        required: true
        description: "Fullt navn på artisten"
      - name: shortTitle
        label: Kort navn
        type: string
        description: "Kortere navn som vises på kort. Bruk hvis artistnavnet er veldig langt."
      - name: tagline
        label: Tagline
        type: string
        description: "Kort og snappy beskrivelse som blant annet vises på kort"
      - name: imageAttribution
        label: Fotograf
        type: string
      - name: author
        label: Forfatter
        type: reference
        required: false
        options:
          collection: authors
          label: "{name}"
          image: "{image}"
      - name: venue
        label: Scene
        type: string
        description: "Hvor konserten spilles (f.eks. 'Teltet', 'Buen (Storsalen)')"
      - name: concertStartAt
        label: Konsertstart
        type: date
        options:
          time: true
          format: yyyy-MM-dd HH:mm
        description: "Når konserten starter (f.eks. '2026-07-10 22:00')"
      - name: concertEndAt
        label: Konsertslutt
        type: date
        options:
          time: true
          format: yyyy-MM-dd HH:mm
        description: "Når konserten slutter (f.eks. '2026-07-10 23:30')"
      - name: spotifyUrl
        label: Spotify URL
        type: string
        description: "Lenke til artist på Spotify"
      - name: youtubeUrl
        label: YouTube URL
        type: string
        description: "Lenke til YouTube-video"
      - name: sponsoredByBergesenstiftelsen
        label: Støttet av Bergesenstiftelsen
        type: boolean
        default: false
        description: "Vis logo for Bergesenstiftelsen"
      - name: hideFromProgram
        label: Skjul fra program
        type: boolean
        default: false
        description: "Skjul fra programsiden"
      - name: hideFromArtistList
        label: Skjul fra artistliste
        type: boolean
        default: false
        description: "Skjul fra forsiden"
      - name: releaseAt
        label: Utgivelsesdato
        type: datetime
        description: "Når artisten skal vises (skjules til denne datoen)"
      - name: isFree
        label: Gratis
        type: boolean
        default: false
        description: "Om konserten er gratis"
      - name: requiresFreeTicket
        label: Krever gratisbillett
        type: boolean
        default: false
        description: "Om gratis konsert krever gratisbillett"
      - name: externalTicketUrl
        label: Ekstern billettlenke
        type: string
        description: "Lenke til ekstern billettsalg"
      - name: isMorgensolo
        label: Morgensolo
        type: boolean
        default: false
        description: "Om dette er en morgensolo"
      - name: isBestillingsverk
        label: Bestillingsverk
        type: boolean
        default: false
        description: "Om dette er et bestillingsverk"
      - name: isBarnekonsert
        label: Barnekonsert
        type: boolean
        default: false
        description: "Om dette er en barnekonsert"
      - name: isPlaceholder
        label: Placeholder
        type: boolean
        default: false
        description: "Om dette er en placeholder"
      - name: isNonConcertEvent
        label: Ikke konsert
        type: boolean
        default: false
        description: "Om dette er en annen type event enn en konsert, feks Pride, After Work, etc."
      - name: cancelled
        label: Avlyst
        type: boolean
        default: false
        description: "Om konserten er avlyst"
      - name: order
        label: Rekkefølge
        type: number
        description: "Rekkefølge på forsiden (lavere tall først)"
      - name: externalLink
        label: Ekstern lenke
        type: string
        description: "Ekstern lenke (hvis ikke lokal artistside)"
      - name: body
        label: Innhold
        type: rich-text
        options:
          media: public-images
          path: public/artist
          extensions: [png, jpg, jpeg, webp]

settings:
  content:
    merge: true
